### ISSUE TITLE
[BUG] i cant use powershell in azure (upload era code)

### ISSUE THREAD

**Issue by kimdaehee921102** [Azure/CloudShell#76] opened 2021-02-22 04:55 UTC
when i enter the powershall in azure . i cant type another command... and didnt respond ... 
i don't know why? how can i slove this problem? help me plz....

![image](https://user-images.githubusercontent.com/79435767/108664135-77d2d180-7515-11eb-9e18-fc8ff9ccca83.png)
[](url)
![image](https://user-images.githubusercontent.com/79435767/108664159-80c3a300-7515-11eb-93c6-eba366424ad3.png)
![image](https://user-images.githubusercontent.com/79435767/108664260-b6688c00-7515-11eb-920f-6ffe0a9b2f40.png)

**Comment by edyoung** [comment] 2021-02-22 05:12
Hi. Sorry to see you're having trouble. I can't tell exactly what the problem is.

Has this always happened for you, or did it this work earlier and doesn't work any more?

Could you try:
- open 'bash' instead of PowerShell. Does that work?
- if so, try running 'pwsh'. Does that show you the same problem?
- if so, try running 'pwsh -noprofile' . Does that work any better?

**Comment by kimdaehee921102** [comment] 2021-02-22 05:17
hi  when i enter the powershall it is not respend .... it is era message...
![image](https://user-images.githubusercontent.com/79435767/108665593-9eded280-7518-11eb-9e4d-c91dc6233afb.png)

yes bash is working now 
just powershall problem...

**Comment by kimdaehee921102** [comment] 2021-02-22 05:31
Requesting a Cloud Shell.Succeeded.
Connecting terminal...

Welcome to Azure Cloud Shell

Type "az" to use Azure CLI
Type "help" to learn about Cloud Shell

Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Platform' threw an exception.
 ---> System.IO.IOException: Bad message
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at System.Management.Automation.Platform.SelectProductNameForDirectory(XDG_Type dirpath) in /PowerShell/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:line 343
   at System.Management.Automation.Platform..cctor() in /PowerShell/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs:line 145
   --- End of inner exception stack trace ---
   at System.Management.Automation.Configuration.PowerShellConfig..ctor() in /PowerShell/src/System.Management.Automation/engine/PSConfiguration.cs:line 91
   at System.Management.Automation.Configuration.PowerShellConfig..cctor() in /PowerShell/src/System.Management.Automation/engine/PSConfiguration.cs:line 57
   --- End of inner exception stack trace ---
   at System.Management.Automation.Utils.GetPolicySettingFromConfigFile[T](ConfigScope[] preferenceOrder) in /PowerShell/src/System.Management.Automation/engine/Utils.cs:line 784
   at System.Management.Automation.Utils.GetPolicySetting[T](ConfigScope[] preferenceOrder) in /PowerShell/src/System.Management.Automation/engine/Utils.cs:line 760
   at Microsoft.PowerShell.CommandLineParameterParser.GetConfigurationNameFromGroupPolicy() in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs:line 578
   at Microsoft.PowerShell.ConsoleHost.ParseCommandLine(String[] args) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 289
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs:line 82
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args) in /PowerShell/src/powershell/Program.cs:line 71
Aborted (core dumped)

**Comment by edyoung** [comment] 2021-02-22 05:31
I understand. I do have several other questions though, please see my comment above.

**Comment by kimdaehee921102** [comment] 2021-02-22 07:47
thanks u to help me 
i sloved the problem 
i did detach partition => clouddrive unmont

**Comment by edyoung** [comment] 2021-02-23 00:15
Glad to hear. I'll close this but let us know if you have other issues.

**Closed by edyoung** 2021-02-23 00:15 UTC
Labels: bug
