### ISSUE TITLE
[BUG] SubscriptionNotRegistered and InternalServerError while deploying resources on Azure

### ISSUE THREAD

**Issue by isabellaherrartelopez** [Azure/CloudShell#487] opened 2024-09-18 20:28 UTC
## To Reproduce
```
1. I attempted to deploy a model on Azure AI using the **Microsoft Azure Sponsorship** subscription.
2. The first error occurred during the resource deployment process.
3. I tried to register the missing resource providers after receiving the `SubscriptionNotRegistered` error.
4. Additionally, I attempted to register all resource providers.

Commands you ran
```
az provider register --namespace '*'

## Observed Behavior
```
Error 1: SubscriptionNotRegistered
{"code":"SubscriptionNotRegistered","message":"Resource provider [N/A] isn't registered 
with Subscription [N/A]. Please see troubleshooting guide, available here: 
https://aka.ms/register-resource-provider","details":[],"additionalInfo":[]}

Error 2: InternalServerError
(InternalServerError) Encountered internal server error. Diagnostic information: 
timestamp '20240918T200325Z', subscription id '7144d715-de64-46f5-a04b-0f720d802eeb', 
tracking id '319546b2-a860-4cc7-b7d9-ea93e4ff0f12', request correlation id 
'319546b2-a860-4cc7-b7d9-ea93e4ff0f12'.
Code: InternalServerError
Message: Encountered internal server error. Diagnostic information: timestamp 
'20240918T200325Z', subscription id '7144d715-de64-46f5-a04b-0f720d802eeb', 
tracking id '319546b2-a860-4cc7-b7d9-ea93e4ff0f12', request correlation id 
'319546b2-a860-4cc7-b7d9-ea93e4ff0f12'.

## Expected behavior
```
- The resource should be successfully deployed without errors.
- The resource providers should be registered successfully after running the az provider register --namespace '*' command.

## Is this specific to Cloud Shell?
Please verify if the same issue can be reproduced by running the same tool **outside Cloud Shell** - for example,
by installing it on your own computer. If so, it is likely to be a bug in that tool or in the Azure service it communicates with, 
not in Cloud Shell. Please file the issue with the appropriate project.
```
No, the same issue persists outside of Cloud Shell. I have tried running the commands on my local machine after installing the Azure CLI, and the same errors (`SubscriptionNotRegistered` and `InternalServerError`) occurred. This suggests the issue is related to the Azure service itself, not Cloud Shell.

## Interface information
How are you accessing Cloud Shell - https://shell.azure.com, https://portal.azure.com, via Windows Terminal, or some other method?
If a browser, which Operating System and browser are you using? (ex. Edge on Windows 10)
```
I accessed Cloud Shell via https://portal.azure.com. When trying locally, I used Azure CLI on a Windows 11 machine with Google as the browser.

## Additional context
The problem seems to be related to registering specific resource providers. Even after attempting to manually register all necessary providers (such as `Microsoft.MachineLearningServices`), the issue persisted, which suggests that there may be an internal issue on Azure’s side regarding the registration of providers or deployment of resources.

**Comment by SuperChenSSS** [comment] 2024-09-19 09:23
I also experienced the same issue, anyone with ideas?

**Comment by mbifeld** [comment] 2024-10-08 17:55
Thanks for filing this issue.  Since this is not a Cloud Shell specific issue, we are unable to determine the root cause.  It sounds like it might be a permission issue with the Microsoft Azure Sponsorship subscription.  I recommend filing a support ticket to get help - https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request.

Closing since the issue is not an issue with Cloud Shell.

**Closed by mbifeld** 2024-10-08 17:55 UTC
Labels: bug, Triage-needed
